version: "3.2"

services:
  db:
    image: postgres:12.1
    container_name: k8s_for_rails_db
    environment:
      - POSTGRES_DB=k8s_for_rails_development
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.7
    container_name: k8s_for_rails_redis
    ports:
      - "6379:6379"
