apiVersion: v1
kind: Secret
metadata:
  name: web-secret
  labels:
    app: k8s-for-rails
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9yb290OnBhc3N3MHJkQGRhdGFiYXNlLXNlcnZpY2UvazhzLWZvci1yYWlscw==
