apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: k8s-for-rails
    tier: web
spec:
  type: NodePort
  selector:
    app: k8s-for-rails
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
