apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: k8s-for-rails
    tier: database
spec:
  selector:
    app: k8s-for-rails
    tier: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
